### ISSUE TITLE
juno cli version command should reason about its version

### ISSUE THREAD

**Issue by dennyweiss** [buildwithjuno/cli#17]
When I run

```
juno version
```

it should warn me when my `@junobuild/cli` is not up-to-data to prevent me from having to fight with issues that aren't there anymore because of the fast development.

*reason behind the idea: I ran into an issue with `@junobuild/cli@0.0.18` where I was not able to upgrade mission control from `v0.0.2` to `v0.0.3` because of a bug that the is fixed in the latest version `@junobuild/cli@0.0.21`.*

**Comment by peterpeterparker** [comment]
Thx. Done and released.
