### ISSUE TITLE
Be able to export and import juno profiles for use in CICD 

### ISSUE THREAD

**Issue by dennyweiss** [buildwithjuno/cli#27]
When setting up a CICD pipeline to deploy juno apps we have to set up juno identies in that process.

I propose the following CLI commands to perform these tasks directly with juno CLI:

1. `juno profile:export <profile-name>`
2. `juno profile:import <profile-string>`

To make things easy I propose a composed string that can be used in cicd: `profileName + separator + base64 encoded profile json string`

e.g.

```
juno-app-name-production|eyJ0b2tlbiI6WyJfX0RFTU9fXyIsIl9fREVNT19fIl0sInNhdGVsbGl0ZXMiOlt7InAiOiIwMDAwMC0wMDAwMC0wMDAwMC0wMDAwMC0wMDAiLCJuIjoianVuby1hcHAtbmFtZS1wcm9kdWN0aW9uIn1dLCJtaXNzaW9uQ29udHJvbCI6IjAwMDAwLTAwMDAwLTAwMDAwLTAwMDAwLTAwMCJ9

```

for convenience  I would suggest the following adjustments

3. `juno profile:use <profile-name>` instead of `juno use <profile-name>`
4. `juno profiles` for printing out all profiles

**Comment by peterpeterparker** [comment]
As we discussed, at least in a first step, we skip the import/export and extend the CLI to support reading a token available in the environment variable as `JUNO_TOKEN`.
